-- Safely drop tables and sequences if they already exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FURNITURE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ROOM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE room_seq';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE furniture_seq';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- Create sequences
CREATE SEQUENCE room_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE furniture_seq START WITH 1 INCREMENT BY 1;

-- Create tables
CREATE TABLE ROOM (
    room_id NUMBER PRIMARY KEY,
    room_name VARCHAR2(100) NOT NULL,
    length NUMBER NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL
);

CREATE TABLE FURNITURE (
    furniture_id NUMBER PRIMARY KEY,
    furniture_name VARCHAR2(100) NOT NULL,
    length NUMBER NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL
);

COMMIT;
EXIT;
