-- Safely drop tables and sequences if they already exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER trg_room_delete_archive';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER trg_furniture_delete_archive';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FURNITURE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ROOM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DELETED_ITEMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE room_seq';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE furniture_seq';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- Create sequences
CREATE SEQUENCE room_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE furniture_seq START WITH 1 INCREMENT BY 1;

-- Create tables
CREATE TABLE ROOM (
    room_id NUMBER PRIMARY KEY,
    room_name VARCHAR2(100) NOT NULL,
    length NUMBER NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL
);

CREATE TABLE FURNITURE (
    furniture_id NUMBER PRIMARY KEY,
    furniture_name VARCHAR2(100) NOT NULL,
    length NUMBER NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL
);

CREATE TABLE DELETED_ITEMS (
    source_table VARCHAR2(20) NOT NULL,
    source_id NUMBER NOT NULL,
    item_name VARCHAR2(100) NOT NULL,
    length NUMBER NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL,
    deleted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER trg_room_delete_archive
BEFORE DELETE ON ROOM
FOR EACH ROW
BEGIN
    INSERT INTO DELETED_ITEMS (source_table, source_id, item_name, length, width, height)
    VALUES ('ROOM', :OLD.room_id, :OLD.room_name, :OLD.length, :OLD.width, :OLD.height);
END;
/

CREATE OR REPLACE TRIGGER trg_furniture_delete_archive
BEFORE DELETE ON FURNITURE
FOR EACH ROW
BEGIN
    INSERT INTO DELETED_ITEMS (source_table, source_id, item_name, length, width, height)
    VALUES ('FURNITURE', :OLD.furniture_id, :OLD.furniture_name, :OLD.length, :OLD.width, :OLD.height);
END;
/

COMMIT;
EXIT;
